// <auto-generated />
namespace RedditMvc.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m2m : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m2m));
        
        string IMigrationMetadata.Id
        {
            get { return "201701160440234_m2m"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
